### ISSUE TITLE
does people still use python 2.7.x with this project?

### ISSUE THREAD

**Issue by rosjat** [python-scsi/python-scsi#81]
this more of a  "get a clue" question here since the world should move on to python 3 its sane enough to do it with this project too only question is how to approach it. So if none of you guys really using 2.7.x anymore i will just update the  readme so everyone notice that its going to be python3 only and then start to make things more python 3 compliant. So just leave me a note here

**Comment by Flameeyes** [comment]
FWIW I use this in https://github.com/glucometers-tech/glucometerutils and that one is Python 3.7 minimum.

Although I'm having other issues right now because the package is not available on PyPI as far as I can tell, so I can't even test this.

I was hoping that wrapping sgutils would be enough for me, but it actually does not help at all, in this case, as they don't actually provide a generic interface with it.

**Comment by rosjat** [comment]
well it seems with the cython approach we will move to python 3 anyway so i close this now :)
